import { useEffect, useState, type JSX } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { readAuthLink } from '@/lib/authLink';
import { routes } from '@/lib/routes';
import { reportError } from '@/lib/sentry';

/**
 * Consume an auth credential arriving in the URL, on whatever route it lands.
 *
 * Nothing in this app did that, and the gap broke every email-based sign-in
 * there is. `AuthContext` only ever called `getSession()`, so the app relied
 * entirely on supabase-js's own `detectSessionInUrl` — and that cannot help
 * here, because the client runs `flowType: 'pkce'` while **every link this
 * system produces is implicit-flow**:
 *
 *   - `owner-password-reset` mints its link with `auth.admin.generateLink`.
 *   - Links generated by hand in the Supabase dashboard do the same, and
 *     redirect to the project's Site URL — the salon's *home page*, which had
 *     no auth code on it whatsoever.
 *
 * A PKCE client will not read an implicit fragment: it wants a `?code=` it can
 * trade using a verifier stored when the flow began, which for a server-minted
 * link never existed in this browser. So GoTrue verified the token, issued a
 * session, redirected — and the app silently dropped it. Recovery links
 * reported "no longer valid", and magic links appeared to do nothing but land
 * on the home page.
 *
 * Three shapes are accepted, which is all of them:
 *
 *   1. `?token_hash=…&type=…`  — `verifyOtp`. Flow-agnostic and works on a
 *      different device from the one that asked, which matters because the
 *      owner reads her email on a phone. This is what the reset function now
 *      sends.
 *   2. `#access_token=…&refresh_token=…` — `setSession`. What GoTrue's own
 *      `/auth/v1/verify` redirect produces, and therefore what any
 *      dashboard-generated link produces.
 *   3. `?code=…` — left to supabase-js, which exchanges it when this browser
 *      holds the verifier (a magic link requested from this same browser).
 *
 * Rendered inside the router and above the routes, so it sees the credential
 * before any gate can redirect away from it.
 */
export function AuthLinkHandler(): JSX.Element | null {
  const navigate = useNavigate();
  const [working, setWorking] = useState(false);

  useEffect(() => {
    // `/reset-password` reads its own credential, and `/access/:token` is the
    // customer magic link, which is this app's own scheme rather than GoTrue's.
    const path = window.location.pathname;
    if (path === routes.auth.resetPassword || path.startsWith('/access/')) return;

    const credential = readAuthLink(window.location.search, window.location.hash);
    if (credential === null) return;

    let active = true;
    setWorking(true);

    // `type` is already narrowed to a known literal by `readAuthLink`, so this
    // picks between two constants rather than routing on attacker input.
    const destination =
      credential.kind !== 'error' && credential.type === 'recovery'
        ? routes.auth.resetPassword
        : routes.owner.dashboard;

    void (async () => {
      try {
        if (credential.kind === 'error') {
          throw new Error('Auth link reported an error');
        }

        if (credential.kind === 'token_hash') {
          const { error } = await supabase.auth.verifyOtp({
            token_hash: credential.tokenHash,
            type: credential.type,
          });
          if (error) throw error;
        } else {
          const { error } = await supabase.auth.setSession({
            access_token: credential.accessToken,
            refresh_token: credential.refreshToken,
          });
          if (error) throw error;
        }

        if (!active) return;
        // Replace, so the spent credential leaves both the address bar and the
        // back button.
        void navigate(destination, { replace: true });
      } catch (e) {
        reportError(e, { where: 'AuthLinkHandler' });
        if (!active) return;
        // Send them somewhere real rather than leaving a dead token in the
        // URL of whatever page they happened to land on. There is no public
        // login-shaped path to fall back to any more (the sign-in form lives
        // behind the owner's own secret, changeable URL), so anything other
        // than the reset-password page's own error state goes home.
        void navigate(
          destination === routes.auth.resetPassword ? destination : routes.public.home,
          {
            replace: true,
          },
        );
      } finally {
        if (active) setWorking(false);
      }
    })();

    return () => {
      active = false;
    };
    // Deliberately once, on mount: the credential is in the URL this app was
    // loaded with, and re-running on navigation would try to spend it twice.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!working) return null;

  return (
    <div
      role="status"
      aria-live="polite"
      className="fixed inset-0 z-layer-popover flex items-center justify-center bg-background"
    >
      <p className="text-sm text-muted-foreground">Signing you in…</p>
    </div>
  );
}
